# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- default

pool:
  vmImage: 'vs2017-win2016'

steps:
- checkout: self
  submodules: recursive

- task: CMake@1
  inputs:
    workingDirectory: build-debug
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Debug'
  displayName: 'Prepare CMake debug build'

- task: CMake@1
  inputs:
    workingDirectory: build-release
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release'
  displayName: 'Prepare CMake release build'

- task: CMake@1
  inputs:
    workingDirectory: build-debug
    cmakeArgs: '--build . --config debug'
  displayName: 'Run CMake debug build'

- task: CMake@1
  inputs:
    workingDirectory: build-release
    cmakeArgs: '--build . --config release'
  displayName: 'Run CMake release build'

- publish: build-debug/Debug/community-patch.dll
  artifact: Community Patch (Debug)
- publish: build-release/Release/community-patch.dll
  artifact: Community Patch (Release)
