# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive

- task: CMake@1
  inputs:
    workingDirectory: build-debug
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Debug'
  displayName: 'Run CMake debug build'

- task: CMake@1
  inputs:
    workingDirectory: build-release
    cmakeArgs: '.. -DCMAKE_BUILD_TYPE=Release'
  displayName: 'Run CMake release build'
