name: Build Community Patch

on: [push]

jobs:
  debug:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare debug DLL
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
    - name: Build debug DLL
      run: cmake --build build
    - name: Make artifact
      run: mkdir -p artifact && cp build/Debug/* artifact && cp -R docs/ artifact
    - uses: actions/upload-artifact@master
      with:
        name: community-patch
        path: artifact
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare release DLL
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
    - name: Build release DLL
      run: cmake --build build
    - name: Make artifact
      run: mkdir -p artifact && cp build/Debug/community-patch.dll artifact && cp -R docs/ artifact
    - uses: actions/upload-artifact@master
      with:
        name: community-patch
        path: artifact
