name: Build Community Patch

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare debug DLL
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Debug
    - name: Build debug DLL
      run: cmake --build build
    - uses: actions/upload-artifact@master
      with:
        name: community-patch.dll
        path: build/community-patch.dll
